name: Frontend CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Grant necessary permissions for CodeQL
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      # Temporarily skip the Test step by commenting it out
      # - name: Test
      #   run: npm run test

      # OPTIONAL CodeQL
      - name: GitHub code scanning
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Build Angular for production
        run: npm run build -- --configuration production

      - name: Deploy to Netlify
        run: npx netlify deploy --prod --dir=dist/book-network-ui
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
